services:
    app:
        container_name: ${COMPOSE_PROJECT_NAME}_streamlit
        build:
            context: .
            dockerfile: Dockerfile.streamlit
            args:
                PYTHON_VERSION: ${PYTHON_VERSION}
        env_file:
            - .env
        volumes:
            - ./:/app
        working_dir: /app
        ports:
            - "${STREAMLIT_PORT}:5000"