cookie:
  expiry_days: 100
  key: some_signature_key
  name: some_cookie_name
credentials:
  usernames:
    A12345:
      email: johndoe@example.com
      name: JohnDoe
      password: $2b$12$5CQDrftTR9oiZQKTbEgrUeOVQqmzmTJJrQriHz7kJ1f6RGbnLVuKS
      role: Admin
    B23456:
      email: alice.smith@example.com
      name: AliceSmith
      password: $2b$12$p7khtR0SD0CJ6LbRVRnkLuDG40vBS/zqzMxDF0qLM.bjNsy4ETqYO
      role: User
    C34567:
      email: bobj@example.com
      name: BobJohnson
      password: $2b$12$JO8aLSGFF3Lp.p82X8qNL.bjAUfjG/O6bVuGor6jKPTVNMppzU5LW
      role: User
